theme: jekyll-theme-minimal
title: AvatarScriptLink.NET
description: AvatarScriptLink.NET is a .NET Standard library designed to help accelerate the safe and stable adoption of ScriptLink extensions for the Netsmart myAvatar electronic medical record.